products = [
  {
    '_id': '1',
    'name': 'AirPods Pro (2nd generation)',
    'image': '/images/airpods.jpg',
    'description':
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    'brand': 'Apple',
    'category': 'Electronics',
    'price': 249.00,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '2',
    'name': 'Samsung Galaxy S23 Ultra 5G',
    'image': '/images/phone.jpg',
    'description':
      'Give yourself a smartphone that recognises your emotions and responds appropriately. The Samsung Galaxy S23 5Gs enhanced AI and Nightography feature produces low-light photos and videos that are vivid and colourful from dusk to dawn and back again.',
    'brand': 'Samsung',
    'category': 'Electronics',
    'price': 1374.35,
    'countInStock': 0,
    'rating': 4.0,
    'numReviews': 8,
  },
  {
    '_id': '3',
    'name': 'FUJIFILM instax mini 12 Instant Camera',
    'image': '/images/camera.jpg',
    'description':
      'Compact and cute design. Easily twist the lens to turn on and off. Built-in selfie mirror for easy selfies   Close-up mode with parallax correction',
    'brand': 'FujiFilm',
    'category': 'Electronics',
    'price': 139.95,
    'countInStock': 5,
    'rating': 3,
    'numReviews': 12,
  },
  {
    '_id': '4',
    'name': 'Sony PlayStation 5',
    'image': '/images/playstation.jpg',
    'description':
      'Stunning Games - Marvel at incredible graphics and experience new PS5 features. Breathtaking Immersion - Discover a deeper gaming experience with support for haptic feedback, adaptive triggers, and 3D Audio technology.',
    'brand': 'Sony',
    'category': 'Electronics',
    'price': 399.00,
    'countInStock': 11,
    'rating': 5,
    'numReviews': 12,
  },
  {
    '_id': '5',
    'name': 'Logitech MX Master 3S Performance Wireless Mouse',
    'image': '/images/mouse.jpg',
    'description':
      'FEEL IT – BARELY HEAR IT Introducing Quiet Clicks – create, make and do with the same click feel, but less noise. Quiet Clicks deliver satisfying, soft tactile feedback with 90% less click noise.',
    'brand': 'Logitech',
    'category': 'Electronics',
    'price': 88.80,
    'countInStock': 7,
    'rating': 3.5,
    'numReviews': 10,
  },
  {
    '_id': '6',
    'name': 'AMAZON Echo (4th Gen) Smart Speaker with Alexa - Twilight Blue',
    'image': '/images/alexa.jpg',
    'description':
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    'brand': 'Amazon',
    'category': 'Electronics',
    'price': 99.99,
    'countInStock': 0,
    'rating': 4,
    'numReviews': 12,
  },
]
