export const EXAMPLE_LIST_REQUEST = 'EXAMPLE_LIST_REQUEST'
export const EXAMPLE_LIST_SUCCESS = 'EXAMPLE_LIST_SUCCESS'
export const EXAMPLE_LIST_FAIL = 'EXAMPLE_LIST_FAIL'

export const EXAMPLE_DETAILS_REQUEST = 'EXAMPLE_DETAILS_REQUEST'
export const EXAMPLE_DETAILS_SUCCESS = 'EXAMPLE_DETAILS_SUCCESS'
export const EXAMPLE_DETAILS_FAIL = 'EXAMPLE_DETAILS_FAIL'

export const EXAMPLE_DELETE_REQUEST = 'EXAMPLE_DELETE_REQUEST'
export const EXAMPLE_DELETE_SUCCESS = 'EXAMPLE_DELETE_SUCCESS'
export const EXAMPLE_DELETE_FAIL = 'EXAMPLE_DELETE_FAIL'

export const EXAMPLE_CREATE_REQUEST = 'EXAMPLE_CREATE_REQUEST'
export const EXAMPLE_CREATE_SUCCESS = 'EXAMPLE_CREATE_SUCCESS'
export const EXAMPLE_CREATE_FAIL = 'EXAMPLE_CREATE_FAIL'
export const EXAMPLE_CREATE_RESET = 'EXAMPLE_CREATE_RESET'


export const EXAMPLE_UPDATE_REQUEST = 'EXAMPLE_UPDATE_REQUEST'
export const EXAMPLE_UPDATE_SUCCESS = 'EXAMPLE_UPDATE_SUCCESS'
export const EXAMPLE_UPDATE_FAIL = 'EXAMPLE_UPDATE_FAIL'
export const EXAMPLE_UPDATE_RESET = 'EXAMPLE_UPDATE_RESET'

export const EXAMPLE_TOP_REQUEST = 'EXAMPLE_TOP_REQUEST'
export const EXAMPLE_TOP_SUCCESS = 'EXAMPLE_TOP_SUCCESS'
export const EXAMPLE_TOP_FAIL = 'EXAMPLE_TOP_FAIL'