export const KONTRATA_LIST_REQUEST = 'KONTRATA_LIST_REQUEST'
export const KONTRATA_LIST_SUCCESS = 'KONTRATA_LIST_SUCCESS'
export const KONTRATA_LIST_FAIL = 'KONTRATA_LIST_FAIL'

export const KONTRATA_DETAILS_REQUEST = 'KONTRATA_DETAILS_REQUEST'
export const KONTRATA_DETAILS_SUCCESS = 'KONTRATA_DETAILS_SUCCESS'
export const KONTRATA_DETAILS_FAIL = 'KONTRATA_DETAILS_FAIL'

export const KONTRATA_DELETE_REQUEST = 'KONTRATA_DELETE_REQUEST'
export const KONTRATA_DELETE_SUCCESS = 'KONTRATA_DELETE_SUCCESS'
export const KONTRATA_DELETE_FAIL = 'KONTRATA_DELETE_FAIL'

export const KONTRATA_CREATE_REQUEST = 'KONTRATA_CREATE_REQUEST'
export const KONTRATA_CREATE_SUCCESS = 'KONTRATA_CREATE_SUCCESS'
export const KONTRATA_CREATE_FAIL = 'KONTRATA_CREATE_FAIL'
export const KONTRATA_CREATE_RESET = 'KONTRATA_CREATE_RESET'


export const KONTRATA_UPDATE_REQUEST = 'KONTRATA_UPDATE_REQUEST'
export const KONTRATA_UPDATE_SUCCESS = 'KONTRATA_UPDATE_SUCCESS'
export const KONTRATA_UPDATE_FAIL = 'KONTRATA_UPDATE_FAIL'
export const KONTRATA_UPDATE_RESET = 'KONTRATA_UPDATE_RESET'
