export const PUNTORI_LIST_REQUEST = 'PUNTORI_LIST_REQUEST'
export const PUNTORI_LIST_SUCCESS = 'PUNTORI_LIST_SUCCESS'
export const PUNTORI_LIST_FAIL = 'PUNTORI_LIST_FAIL'

export const PUNTORI_DETAILS_REQUEST = 'PUNTORI_DETAILS_REQUEST'
export const PUNTORI_DETAILS_SUCCESS = 'PUNTORI_DETAILS_SUCCESS'
export const PUNTORI_DETAILS_FAIL = 'PUNTORI_DETAILS_FAIL'

export const PUNTORI_DELETE_REQUEST = 'PUNTORI_DELETE_REQUEST'
export const PUNTORI_DELETE_SUCCESS = 'PUNTORI_DELETE_SUCCESS'
export const PUNTORI_DELETE_FAIL = 'PUNTORI_DELETE_FAIL'

export const PUNTORI_CREATE_REQUEST = 'PUNTORI_CREATE_REQUEST'
export const PUNTORI_CREATE_SUCCESS = 'PUNTORI_CREATE_SUCCESS'
export const PUNTORI_CREATE_FAIL = 'PUNTORI_CREATE_FAIL'
export const PUNTORI_CREATE_RESET = 'PUNTORI_CREATE_RESET'


export const PUNTORI_UPDATE_REQUEST = 'PUNTORI_UPDATE_REQUEST'
export const PUNTORI_UPDATE_SUCCESS = 'PUNTORI_UPDATE_SUCCESS'
export const PUNTORI_UPDATE_FAIL = 'PUNTORI_UPDATE_FAIL'
export const PUNTORI_UPDATE_RESET = 'PUNTORI_UPDATE_RESET'
