export const SATELLITE_LIST_REQUEST = 'SATELLITE_LIST_REQUEST'
export const SATELLITE_LIST_SUCCESS = 'SATELLITE_LIST_SUCCESS'
export const SATELLITE_LIST_FAIL = 'SATELLITE_LIST_FAIL'

export const SATELLITE_DETAILS_REQUEST = 'SATELLITE_DETAILS_REQUEST'
export const SATELLITE_DETAILS_SUCCESS = 'SATELLITE_DETAILS_SUCCESS'
export const SATELLITE_DETAILS_FAIL = 'SATELLITE_DETAILS_FAIL'

export const SATELLITE_DELETE_REQUEST = 'SATELLITE_DELETE_REQUEST'
export const SATELLITE_DELETE_SUCCESS = 'SATELLITE_DELETE_SUCCESS'
export const SATELLITE_DELETE_FAIL = 'SATELLITE_DELETE_FAIL'

export const SATELLITE_CREATE_REQUEST = 'SATELLITE_CREATE_REQUEST'
export const SATELLITE_CREATE_SUCCESS = 'SATELLITE_CREATE_SUCCESS'
export const SATELLITE_CREATE_FAIL = 'SATELLITE_CREATE_FAIL'
export const SATELLITE_CREATE_RESET = 'SATELLITE_CREATE_RESET'


export const SATELLITE_UPDATE_REQUEST = 'SATELLITE_UPDATE_REQUEST'
export const SATELLITE_UPDATE_SUCCESS = 'SATELLITE_UPDATE_SUCCESS'
export const SATELLITE_UPDATE_FAIL = 'SATELLITE_UPDATE_FAIL'
export const SATELLITE_UPDATE_RESET = 'SATELLITE_UPDATE_RESET'
