export const SHEMBULLIDYTE_LIST_REQUEST = 'SHEMBULLIDYTE_LIST_REQUEST'
export const SHEMBULLIDYTE_LIST_SUCCESS = 'SHEMBULLIDYTE_LIST_SUCCESS'
export const SHEMBULLIDYTE_LIST_FAIL = 'SHEMBULLIDYTE_LIST_FAIL'

export const SHEMBULLIDYTE_DETAILS_REQUEST = 'SHEMBULLIDYTE_DETAILS_REQUEST'
export const SHEMBULLIDYTE_DETAILS_SUCCESS = 'SHEMBULLIDYTE_DETAILS_SUCCESS'
export const SHEMBULLIDYTE_DETAILS_FAIL = 'SHEMBULLIDYTE_DETAILS_FAIL'

export const SHEMBULLIDYTE_DELETE_REQUEST = 'SHEMBULLIDYTE_DELETE_REQUEST'
export const SHEMBULLIDYTE_DELETE_SUCCESS = 'SHEMBULLIDYTE_DELETE_SUCCESS'
export const SHEMBULLIDYTE_DELETE_FAIL = 'SHEMBULLIDYTE_DELETE_FAIL'

export const SHEMBULLIDYTE_CREATE_REQUEST = 'SHEMBULLIDYTE_CREATE_REQUEST'
export const SHEMBULLIDYTE_CREATE_SUCCESS = 'SHEMBULLIDYTE_CREATE_SUCCESS'
export const SHEMBULLIDYTE_CREATE_FAIL = 'SHEMBULLIDYTE_CREATE_FAIL'
export const SHEMBULLIDYTE_CREATE_RESET = 'SHEMBULLIDYTE_CREATE_RESET'


export const SHEMBULLIDYTE_UPDATE_REQUEST = 'SHEMBULLIDYTE_UPDATE_REQUEST'
export const SHEMBULLIDYTE_UPDATE_SUCCESS = 'SHEMBULLIDYTE_UPDATE_SUCCESS'
export const SHEMBULLIDYTE_UPDATE_FAIL = 'SHEMBULLIDYTE_UPDATE_FAIL'
export const SHEMBULLIDYTE_UPDATE_RESET = 'SHEMBULLIDYTE_UPDATE_RESET'
