export const SHEMBULLIPARE_LIST_REQUEST = 'SHEMBULLIPARE_LIST_REQUEST'
export const SHEMBULLIPARE_LIST_SUCCESS = 'SHEMBULLIPARE_LIST_SUCCESS'
export const SHEMBULLIPARE_LIST_FAIL = 'SHEMBULLIPARE_LIST_FAIL'

export const SHEMBULLIPARE_DETAILS_REQUEST = 'SHEMBULLIPARE_DETAILS_REQUEST'
export const SHEMBULLIPARE_DETAILS_SUCCESS = 'SHEMBULLIPARE_DETAILS_SUCCESS'
export const SHEMBULLIPARE_DETAILS_FAIL = 'SHEMBULLIPARE_DETAILS_FAIL'

export const SHEMBULLIPARE_DELETE_REQUEST = 'SHEMBULLIPARE_DELETE_REQUEST'
export const SHEMBULLIPARE_DELETE_SUCCESS = 'SHEMBULLIPARE_DELETE_SUCCESS'
export const SHEMBULLIPARE_DELETE_FAIL = 'SHEMBULLIPARE_DELETE_FAIL'

export const SHEMBULLIPARE_CREATE_REQUEST = 'SHEMBULLIPARE_CREATE_REQUEST'
export const SHEMBULLIPARE_CREATE_SUCCESS = 'SHEMBULLIPARE_CREATE_SUCCESS'
export const SHEMBULLIPARE_CREATE_FAIL = 'SHEMBULLIPARE_CREATE_FAIL'
export const SHEMBULLIPARE_CREATE_RESET = 'SHEMBULLIPARE_CREATE_RESET'


export const SHEMBULLIPARE_UPDATE_REQUEST = 'SHEMBULLIPARE_UPDATE_REQUEST'
export const SHEMBULLIPARE_UPDATE_SUCCESS = 'SHEMBULLIPARE_UPDATE_SUCCESS'
export const SHEMBULLIPARE_UPDATE_FAIL = 'SHEMBULLIPARE_UPDATE_FAIL'
export const SHEMBULLIPARE_UPDATE_RESET = 'SHEMBULLIPARE_UPDATE_RESET'
