# Generated by Django 4.2.4 on 2023-09-05 09:03

from django.db import migrations, models

def set_default_image(apps, schema_editor):
    Product = apps.get_model('base', 'Product')
    default_image_path = 'mace.jpg'
    Product.objects.filter(image='').update(image=default_image_path)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RunPython(set_default_image),
    ]
