# Generated by Django 4.2.4 on 2024-02-05 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_example'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='rating',
        ),
    ]
