# Generated by Django 4.2.4 on 2024-02-05 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_example_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='example',
            name='category',
        ),
        migrations.RemoveField(
            model_name='example',
            name='numReviews',
        ),
    ]
