# Generated by Django 4.2.4 on 2024-02-07 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_example_brand_remove_example_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='example',
            old_name='example',
            new_name='shembull',
        ),
    ]
