# Generated by Django 4.2.4 on 2024-02-13 13:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_example_example_shembull'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
