# Generated by Django 4.2.4 on 2024-02-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_example_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='example',
            old_name='id',
            new_name='example_id',
        ),
    ]
