# Generated by Django 4.2.4 on 2024-03-06 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0013_shembullipare_shembullidyte'),
    ]

    operations = [
        migrations.AddField(
            model_name='shembullidyte',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shembullipare',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shembullidyte',
            name='shembulliDyteId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
