# Generated by Django 4.2.4 on 2024-03-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_shembullidyte_user_shembullipare_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shembullidyte',
            name='shembull',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shembullipare',
            name='shembull',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
