# Generated by Django 4.2.4 on 2024-03-07 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_planet_satellite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellite',
            name='planetId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='satellites', to='base.planet'),
        ),
    ]
