# Generated by Django 4.2.4 on 2024-05-14 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0017_alter_satellite_planetid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puntori',
            fields=[
                ('puntoriId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('isActive', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kontrata',
            fields=[
                ('kontrataId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('startDate', models.IntegerField(blank=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('puntoriId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kontratat', to='base.puntori')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
