# Generated by Django 4.2.4 on 2024-05-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_puntori_kontrata'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontrata',
            name='startData',
            field=models.DateField(blank=True, null=True),
        ),
    ]
